### ISSUE TITLE
[Chain So API] CORS policy: No 'Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by marchelhutagalung** [yfgeek/BlockVotes#16]
`Access to XMLHttpRequest at 'https://chain.so/api/v2/get_tx_unspent/BTCTEST/muqFUCLSyCmLh114z4hF8sBqY6AKTjntdE' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

i found this error when api calls get chain.so

**Comment by RobinJesba** [comment]
https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en

Adding this extension worked for me!
