### ISSUE TITLE
I need help..

### ISSUE THREAD

**Issue by Patrick-Elvis** [yfgeek/BlockVotes#2]
When I set it up on Localhost 
Only html shows...
Like there is no CSS

**Comment by yfgeek** [comment]
@Patrick-Elvis 

> For the whole project, directory `public` is the entrance of the system. If you can not open the page, please check it if is configured correctly in the Nginx or Apache.

```
server {
//.....
    root /www/html/blockvotes/public;
//.....
    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_index index.php;
        fastcgi_pass 127.0.0.1:9000;
    }
}
```

And please write down your OS, MySQL version and PHP version.

**Comment by Patrick-Elvis** [comment]
![blockvotes](https://user-images.githubusercontent.com/29231486/40125930-c1f4f40a-5934-11e8-9495-8a0fe2ef415a.PNG)

Windows 10
PHP version: 7.2.5
Version information: 4.8.0.1

**Comment by Patrick-Elvis** [comment]
Then the passwords ?

**Comment by yfgeek** [comment]
@Patrick-Elvis 
Please do not set the system as a subdirectory.
Try to move it to the top directory and open the link 
http://localhost/

Registration Authority Account
username ra 
password 123456

Election Authority Account
username ea 
password 123456

**Comment by Patrick-Elvis** [comment]
Thanks Bro 👊

**Comment by Patrick-Elvis** [comment]
Thanks bro 👊

**Comment by Mani-07hub** [comment]
I'm getting the same issue that when I'm open localhost through XAMPP it only shows HTML without CSS.How can i set the system as a top directory?
